version: '3.9'

services:
  mysql:
    image: mysql:8.0
    container_name: jaqops-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: jaqops
      MYSQL_USER: jaqops
      MYSQL_PASSWORD: PleaseChangeThisPassword
    volumes:
      - mysql-data:/var/lib/mysql
    ports:
      - "3306:3306"
    restart: unless-stopped
    command: --default-authentication-plugin=mysql_native_password

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: jaqops-backend
    depends_on:
      - mysql
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=mysql;Database=jaqops;User=jaqops;Password=PleaseChangeThisPassword;
    ports:
      - "5000:8080"
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: jaqops-frontend
    ports:
      - "3000:80"
    restart: unless-stopped
    depends_on:
      - backend

volumes:
  mysql-data:
